// Electron app-shell auto-updater. Uses electron-updater (Squirrel.Mac under
// the hood) to download + install new versions of the Unclaw.app bundle , 
// the only category the content-side updateCoordinator can't touch, because
// a code-signed .app's executable + main-process JS lives inside the bundle
// itself.
//
// Squirrel needs:
//   1. `publish:` config in electron-builder (added in package.json)
//   2. `latest-mac.yml` published next to the DMG/zip on R2, generated by
//      electron-builder automatically when `dist:mac` runs WITH publish=true.
//   3. The artifact must be code-signed + notarized (already in our pipeline).
//
// Flow:
//   - On launch, checkForUpdates() fires asynchronously.
//   - On `update-available`, we record the version + reflect it in the
//     UpdateOverlay snapshot via the bridge in updateCoordinator.
//   - On `update-downloaded`, we mark the `app` category as 'ready' +
//     `restartRequired: true`.
//   - On user click "Restart now" → app.relaunch() works for content-only;
//     for app-shell we MUST go through autoUpdater.quitAndInstall() so
//     Squirrel actually swaps the bundle.

import { app, BrowserWindow } from 'electron';
import { autoUpdater, UpdateInfo, ProgressInfo } from 'electron-updater';

// Cached state surfaced to updateCoordinator. updateCoordinator merges this
// into its own per-category snapshot so the UI shows app-shell + content
// updates in one unified list.
export interface AppShellState {
  /** 'idle' before first check, 'checking' during the manifest GET,
   *  'available' when a newer version was found and is downloading,
   *  'downloading' is reported via onProgress, 'ready' when fully
   *  staged and waiting for the user to restart, 'up-to-date' if the
   *  remote version equals the installed, 'failed' on any error. */
  state: 'idle' | 'checking' | 'available' | 'downloading' | 'ready' | 'up-to-date' | 'failed';
  installedVersion: string;
  remoteVersion: string | null;
  progressPct: number | null;
  detail: string | null;
}

let cached: AppShellState = {
  state: 'idle',
  installedVersion: app.getVersion(),
  remoteVersion: null,
  progressPct: null,
  detail: null,
};

type Listener = (state: AppShellState) => void;
const listeners = new Set<Listener>();

export function getAppShellState(): AppShellState {
  return cached;
}

export function subscribeAppShell(cb: Listener): () => void {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

function publish(): void {
  for (const cb of listeners) {
    try { cb(cached); } catch { /* listener crash shouldn't take down updater */ }
  }
}

// ----------------------------------------------------------------------
// Wiring
// ----------------------------------------------------------------------

let wired = false;

/**
 * Kick the autoUpdater for this session. Idempotent, second call is a
 * no-op. Pass the main window for log forwarding.
 */
export function startAppShellUpdater(window: BrowserWindow | null): void {
  if (wired) return;
  if (!app.isPackaged) {
    // Dev runs don't go through Squirrel, leave state as 'up-to-date'
    // so updateCoordinator surfaces a clean "no work" for the `app` row.
    cached = { ...cached, state: 'up-to-date' };
    publish();
    return;
  }
  wired = true;

  // Quiet electron-updater's own logger, we forward the events we care
  // about. Without this, every download chunk floods stdout.
  autoUpdater.autoDownload = true;     // download in background as soon as one is found
  autoUpdater.autoInstallOnAppQuit = true; // belt-and-suspenders: if the user
                                      // never clicks "Restart now", the update
                                      // applies on the next clean quit.
  autoUpdater.disableWebInstaller = true;

  autoUpdater.on('checking-for-update', () => {
    cached = { ...cached, state: 'checking', detail: 'Looking for app updates…' };
    publish();
    log(window, '[app-updater] checking for updates');
  });

  autoUpdater.on('update-available', (info: UpdateInfo) => {
    cached = {
      ...cached,
      state: 'available',
      remoteVersion: info.version,
      progressPct: 0,
      detail: `App ${info.version} available, downloading…`,
    };
    publish();
    log(window, `[app-updater] update available: ${info.version}`);
  });

  autoUpdater.on('update-not-available', (info: UpdateInfo) => {
    cached = {
      ...cached,
      state: 'up-to-date',
      remoteVersion: info.version,
      detail: null,
    };
    publish();
    log(window, `[app-updater] up to date at ${info.version}`);
  });

  autoUpdater.on('download-progress', (progress: ProgressInfo) => {
    cached = {
      ...cached,
      state: 'downloading',
      progressPct: progress.percent / 100,
      detail: `${Math.round(progress.percent)}% · ` +
        `${(progress.bytesPerSecond / 1e6).toFixed(1)} MB/s`,
    };
    publish();
  });

  autoUpdater.on('update-downloaded', (info: UpdateInfo) => {
    cached = {
      ...cached,
      state: 'ready',
      remoteVersion: info.version,
      progressPct: 1,
      detail: `App ${info.version} ready. Restart to apply.`,
    };
    publish();
    log(window, `[app-updater] downloaded ${info.version}, pending restart`);
  });

  autoUpdater.on('error', (err) => {
    cached = {
      ...cached,
      state: 'failed',
      detail: err.message || String(err),
    };
    publish();
    log(window, `[app-updater] error: ${err.message || err}`);
  });

  // Kick the check. We don't await, Squirrel does its work in the
  // background and we surface progress via events. A network failure
  // logs + transitions to 'failed' but never blocks anything.
  autoUpdater.checkForUpdates().catch((err) => {
    log(window, `[app-updater] checkForUpdates rejected: ${err.message || err}`);
  });
}

/**
 * Apply a downloaded update by quitting + installing. Squirrel relaunches
 * Unclaw post-install. Returns immediately (the call doesn't return until
 * the process is replaced).
 */
export function quitAndInstallAppUpdate(): void {
  if (!app.isPackaged) {
    // In dev, fall back to a plain relaunch so the overlay's "Restart now"
    // button does SOMETHING useful even when Squirrel isn't wired.
    app.relaunch();
    app.exit(0);
    return;
  }
  autoUpdater.quitAndInstall(false, true);
}

function log(window: BrowserWindow | null, line: string): void {
  // eslint-disable-next-line no-console
  console.log(line);
  if (!window || window.isDestroyed()) return;
  window.webContents.send('update:log', line);
}
